import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,authorizeLocation,worldFor,recordView,respond,stopSharing,expire,PEOPLE} from '../server/privacy.js';
import {DemoRoutingProvider} from '../server/routing.js';
const NOW=1780000000000;
function request(w,from='alex',to='sarah'){const r={id:'test-request',from,to,status:'pending',kind:'meetup',createdAt:NOW};w.requests.push(r);return r;}
test('normal friends receive only a fixed region center, never the actual location',()=>{const w=createWorld(NOW);const a=authorizeLocation(w,'alex','sarah',NOW);assert.equal(a.precision,'approximate');assert.deepEqual(a.coordinate,w.users.sarah.areaCenter);assert.notDeepEqual(a.coordinate,w.users.sarah.actual);assert.equal('actual' in a,false);const payload=worldFor(w,'alex',NOW);assert.equal(JSON.stringify(payload.people).includes('"actual"'),false);});
test('nearby returns an approximate boolean with no distance',()=>{const w=createWorld(NOW);const s=worldFor(w,'alex',NOW).people.find(p=>p.id==='sarah');assert.equal(s.nearby,true);assert.equal('distance' in s,false);assert.equal('meters' in s,false);});
test('requesting alone does not unlock precise location',()=>{const w=createWorld(NOW);request(w);assert.equal(authorizeLocation(w,'alex','sarah',NOW).precision,'approximate');});
test('only the recipient can approve a request',()=>{const w=createWorld(NOW);request(w);assert.throws(()=>respond(w,'alex','test-request','allow','15m',NOW));assert.equal(w.grants.length,0);});
test('explicit approval grants precise access only to the authorized viewer',()=>{const w=createWorld(NOW);request(w);respond(w,'sarah','test-request','allow','15m',NOW);assert.equal(authorizeLocation(w,'alex','sarah',NOW).precision,'precise');assert.equal(authorizeLocation(w,'jamie','sarah',NOW).precision,'approximate');});
test('expiry returns sharing to approximate without client action',()=>{const w=createWorld(NOW);request(w);respond(w,'sarah','test-request','allow','15m',NOW);expire(w,NOW+900001);assert.equal(authorizeLocation(w,'alex','sarah',NOW+900001).precision,'approximate');assert.equal(w.grants.length,0);});
test('halfway approval does not grant exact starting positions',()=>{const w=createWorld(NOW);request(w);respond(w,'sarah','test-request','halfway','15m',NOW);assert.equal(w.grants.length,0);assert.equal(authorizeLocation(w,'alex','sarah',NOW).precision,'approximate');});
test('Ghost Mode revokes grants, pending requests, nearby and journey exposure',()=>{const w=createWorld(NOW);request(w);respond(w,'sarah','test-request','allow','15m',NOW);w.journeys.push({id:'j',owner:'sarah',audience:['alex'],status:'on the way',startedAt:NOW,duration:75000,progress:0,destination:{name:'Pier 17'}});stopSharing(w,'sarah');assert.equal(authorizeLocation(w,'alex','sarah',NOW),null);assert.equal(w.grants.length,0);const payload=worldFor(w,'alex',NOW);assert.equal(payload.people.find(p=>p.id==='sarah').nearby,false);assert.equal(payload.journeys.length,0);});
test('blocking and friendship removal revoke precise access',()=>{const w=createWorld(NOW);request(w);respond(w,'sarah','test-request','allow','15m',NOW);w.users.sarah.blocked.push('alex');expire(w,NOW);assert.equal(authorizeLocation(w,'alex','sarah',NOW),null);assert.equal(w.grants.length,0);w.users.sarah.blocked=[];w.users.alex.friends=[];assert.equal(authorizeLocation(w,'alex','sarah',NOW),null);});
test('passive World fetches create no view events; detail views aggregate by day',()=>{const w=createWorld(NOW);worldFor(w,'alex',NOW);assert.equal(w.views.length,0);recordView(w,'alex','sarah',NOW);recordView(w,'alex','sarah',NOW+1000);assert.equal(w.views.length,1);assert.equal(w.views[0].count,2);assert.equal(worldFor(w,'sarah',NOW).views[0].name,'Alex');});
test('stale locations are marked unavailable and never presented as nearby',()=>{const w=createWorld(NOW);w.users.sarah.updatedAt=NOW-31*60000;const payload=worldFor(w,'alex',NOW);const p=payload.people.find(p=>p.id==='sarah');assert.equal(p.location.precision,'unavailable');assert.equal(p.location.coordinate,undefined);assert.equal(p.nearby,false);});
test('arrival is automatic and only notifies the selected audience once',()=>{const w=createWorld(NOW);w.journeys.push({id:'journey',owner:'sarah',audience:['alex'],startedAt:NOW,duration:75000,status:'leaving',progress:0,destination:{name:'Pier 17'}});expire(w,NOW+75001);expire(w,NOW+76000);assert.equal(w.journeys[0].status,'arrived');assert.equal(w.notifications.length,1);assert.deepEqual(w.notifications[0].audience,['alex']);});
test('demo routing follows bundled real road vertices for all supported modes',()=>{const r=new DemoRoutingProvider();for(const mode of ['walk','cycle','drive','transit']){const route=r.route(PEOPLE[0].actual,PEOPLE[1].actual,mode);assert.equal(route.mode,mode);assert.equal(route.simulated,true);assert.ok(route.minutes>0);assert.ok(route.meters>0);assert.ok(route.geometry.coordinates.length>2);}assert.throws(()=>r.route(PEOPLE[0].actual,PEOPLE[1].actual,'fly'));});
